services:
  - type: web
    name: kim-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-service-account.json
      - key: CUT_INTERVAL_DAYS
        value: 15
      - key: PORT
        value: 10000
